# Generated by Django 5.2.17 on 2026-09-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attn_default', models.CharField(default='UR DEPARTMENT', max_length=200, verbose_name='ATTN default')),
                ('client_default', models.CharField(default='WORLDTRIPS', max_length=200, verbose_name='Client default')),
                ('doctor_default', models.CharField(default='RICHARD ABDALLAH', help_text='Printed after "Dr." in the letter.', max_length=200, verbose_name='Doctor default')),
                ('pdf_root_folder', models.CharField(blank=True, help_text='Local or UNC path, e.g. \\server\\claims. Access passes the sub-folder name.', max_length=500, verbose_name='PDF root folder')),
                ('pdf_filename_pattern', models.CharField(default='CLINICALS REQUEST-{member_name}-SENT{MMDDYY}.pdf', help_text='Placeholders: {member_name} {policy_id} {case_encounter} {MMDDYY} {YYYYMMDD}', max_length=200, verbose_name='PDF filename pattern')),
                ('template', models.FileField(blank=True, upload_to='templates/', verbose_name='Word template (.docx)')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_encounter', models.CharField(max_length=100, unique=True, verbose_name='Case/Encounter')),
                ('policy_id', models.CharField(max_length=100, verbose_name='Policy ID')),
                ('member_name', models.CharField(max_length=200)),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('admission', models.CharField(max_length=200)),
                ('attn', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('doctor', models.CharField(max_length=200)),
                ('folder_name', models.CharField(max_length=300)),
                ('pdf_path', models.CharField(blank=True, max_length=1000)),
                ('docx_path', models.CharField(blank=True, max_length=1000)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
    ]
