# Generated by Django 5.2.17 on 2026-09-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='pdf_root_folder',
            field=models.CharField(blank=True, help_text='Local or UNC path, e.g. \\\\server\\claims. Access passes the sub-folder name.', max_length=500, verbose_name='PDF root folder'),
        ),
    ]
