# Generated by Django 5.2.17 on 2026-09-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_handoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.CharField(blank=True, db_index=True, max_length=150)),
                ('windows_user', models.CharField(blank=True, max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(choices=[('form_opened', 'Letter form opened'), ('letter_created', 'Letter created'), ('letter_updated', 'Letter updated'), ('letter_failed', 'Letter generation failed'), ('pdf_downloaded', 'PDF downloaded'), ('pdf_regenerated', 'PDF regenerated'), ('list_viewed', 'Letters list viewed'), ('settings_changed', 'Settings changed'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login failed'), ('lockout', 'Account locked out')], db_index=True, max_length=32)),
                ('case_encounter', models.CharField(blank=True, db_index=True, max_length=100)),
                ('detail', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
    ]
