# Generated by Django 5.2.17 on 2026-09-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_auditevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='pdf_root_folder',
        ),
        migrations.AlterField(
            model_name='letter',
            name='folder_name',
            field=models.CharField(help_text='Full destination folder supplied by the launcher.', max_length=500, verbose_name='Folder'),
        ),
    ]
