# Generated by Django 5.2.17 on 2026-09-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_folder_full_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='case_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Case location'),
        ),
        migrations.AddField(
            model_name='letter',
            name='case_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Case type'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='pdf_filename_pattern',
            field=models.CharField(default='{case_encounter}-{case_location}-{case_type}-CLINICALS REQUEST-{member_name}-SENT{MMDDYY}-{user}.pdf', help_text='Placeholders: {case_encounter} {policy_id} {member_name} {case_location} {case_type} {user} {MMDDYY} {YYYYMMDD}. Values the launcher did not send are left out and the extra separators removed.', max_length=200, verbose_name='PDF filename pattern'),
        ),
    ]
