<#
Phase 1.2–1.4 — PostgreSQL: SCRAM auth, TLS-only local connections, safe logging.
Run in an elevated PowerShell on the database server AFTER 01-database-roles.sql.

  .\02-postgresql-hardening.ps1 -PgVersion 18 -CertPath C:\certs\server.crt -KeyPath C:\certs\server.key

Without -CertPath/-KeyPath a self-signed certificate is generated (fine for
localhost-only connections; use sslmode = require in mapinc.ini). With a
certificate from the domain CA, clients can use sslmode = verify-full.
#>
param(
    [string]$PgVersion = "18",
    [string]$CertPath = "",
    [string]$KeyPath = "",
    [string]$SuperuserPassword = $(Read-Host "postgres superuser password")
)
$ErrorActionPreference = "Stop"
$bin  = "C:\Program Files\PostgreSQL\$PgVersion\bin"
$data = "C:\Program Files\PostgreSQL\$PgVersion\data"
$svc  = "postgresql-x64-$PgVersion"
$env:PGPASSWORD = $SuperuserPassword

function Invoke-Sql([string]$sql) { & "$bin\psql.exe" -U postgres -h localhost -d postgres -v ON_ERROR_STOP=1 -c $sql }

# --- certificate --------------------------------------------------------------
if ($CertPath -and $KeyPath) {
    Copy-Item $CertPath "$data\server.crt" -Force
    Copy-Item $KeyPath  "$data\server.key" -Force
} elseif (-not (Test-Path "$data\server.crt")) {
    Write-Host "Generating a self-signed certificate (localhost only)..."
    $cert = New-SelfSignedCertificate -DnsName "localhost", $env:COMPUTERNAME -CertStoreLocation Cert:\LocalMachine\My `
            -KeyExportPolicy Exportable -NotAfter (Get-Date).AddYears(5) -KeyAlgorithm RSA -KeyLength 2048
    $pfx = "$env:TEMP\pg.pfx"; $pw = ConvertTo-SecureString "temp" -AsPlainText -Force
    Export-PfxCertificate -Cert $cert -FilePath $pfx -Password $pw | Out-Null
    # openssl ships with PostgreSQL
    & "$bin\openssl.exe" pkcs12 -in $pfx -clcerts -nokeys -out "$data\server.crt" -passin pass:temp
    & "$bin\openssl.exe" pkcs12 -in $pfx -nocerts -nodes -out "$data\server.key" -passin pass:temp
    Remove-Item $pfx
}
# the key must be readable only by the service account and Administrators
icacls "$data\server.key" /inheritance:r /grant:r "NT AUTHORITY\NetworkService:R" "BUILTIN\Administrators:F" | Out-Null

# --- postgresql.conf via ALTER SYSTEM (written to postgresql.auto.conf) -------
$settings = @{
    "password_encryption"        = "'scram-sha-256'"
    "ssl"                        = "on"
    "ssl_cert_file"              = "'server.crt'"
    "ssl_key_file"               = "'server.key'"
    "ssl_min_protocol_version"   = "'TLSv1.2'"
    "listen_addresses"           = "'localhost'"
    "logging_collector"          = "on"
    "log_destination"            = "'csvlog'"
    "log_directory"              = "'log'"
    "log_filename"               = "'postgresql-%Y-%m-%d.log'"
    "log_rotation_age"           = "'1d'"
    "log_truncate_on_rotation"   = "off"
    "log_connections"            = "on"
    "log_disconnections"         = "on"
    "log_statement"              = "'ddl'"
    "log_min_duration_statement" = "-1"
    "log_line_prefix"            = "'%m [%p] user=%u db=%d app=%a host=%h '"
}
foreach ($k in $settings.Keys) { Invoke-Sql "ALTER SYSTEM SET $k = $($settings[$k]);" }

# --- pg_hba.conf: SCRAM over TLS from localhost only --------------------------
Copy-Item "$data\pg_hba.conf" "$data\pg_hba.conf.bak-$(Get-Date -Format yyyyMMddHHmm)"
@"
# Generated by deploy\02-postgresql-hardening.ps1 — TLS + SCRAM from localhost only.
# TYPE     DATABASE   USER            ADDRESS         METHOD
hostssl    mapinc     mapinc_app      127.0.0.1/32    scram-sha-256
hostssl    mapinc     mapinc_owner    127.0.0.1/32    scram-sha-256
hostssl    mapinc     mapinc_report   127.0.0.1/32    scram-sha-256
hostssl    all        postgres        127.0.0.1/32    scram-sha-256
hostssl    mapinc     mapinc_app      ::1/128         scram-sha-256
hostssl    all        postgres        ::1/128         scram-sha-256
"@ | Set-Content "$data\pg_hba.conf" -Encoding ascii

Restart-Service $svc
Start-Sleep 3

# Passwords must be re-set AFTER password_encryption changed so they are stored as SCRAM.
Write-Host "Re-enter the role passwords so they are stored with SCRAM-SHA-256:"
foreach ($role in "mapinc_owner", "mapinc_app", "mapinc_report", "postgres") {
    $p = Read-Host "$role password"
    Invoke-Sql "ALTER ROLE $role PASSWORD '$p';"
}

Write-Host "`nVerification:"
& "$bin\psql.exe" "host=localhost dbname=mapinc user=postgres sslmode=require" -c "SELECT ssl, version FROM pg_stat_ssl WHERE pid = pg_backend_pid();"
Write-Host "A non-SSL connection must now FAIL:"
& "$bin\psql.exe" "host=localhost dbname=mapinc user=postgres sslmode=disable" -c "SELECT 1" 2>&1 | Select-Object -First 2
